/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author thoma
 */
public class IngresarRegistros extends javax.swing.JFrame {

    /**
     * Creates new form IngresarRegistros
     */
    public IngresarRegistros(String nombre_registro) {
        initComponents();
        ocultarPaneles();
        if(nombre_registro.equalsIgnoreCase("usuario")){
            titulo_txt.setText("Ingresar Usuario");
            ingresarPersona.setVisible(true);
            ingresarUsuario.setVisible(true);
        }else if(nombre_registro.equalsIgnoreCase("vendedor")){
            titulo_txt.setText("Ingresar Vendedor");
            ingresarPersona.setVisible(true);
            ingresarVendedor.setVisible(true);
        }else if(nombre_registro.equalsIgnoreCase("desarrollador")){

        }else if(nombre_registro.equalsIgnoreCase("videojuego")){

        }else{
                
        }
    }
    private void ocultarPaneles(){
        ingresarPersona.setVisible(false);
        ingresarUsuario.setVisible(false);
        ingresarVendedor.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ingresarPersona = new javax.swing.JPanel();
        titulo_txt = new javax.swing.JLabel();
        rut_txt = new javax.swing.JLabel();
        rut_input = new javax.swing.JTextField();
        jSeparator_rut2 = new javax.swing.JSeparator();
        nombre_txt = new javax.swing.JLabel();
        nombre_input = new javax.swing.JTextField();
        jSeparator_nombre2 = new javax.swing.JSeparator();
        correo_txt = new javax.swing.JLabel();
        correo_input = new javax.swing.JTextField();
        jSeparator_correo2 = new javax.swing.JSeparator();
        comuna_txt = new javax.swing.JLabel();
        comuna_input = new javax.swing.JTextField();
        jSeparator_comuna1 = new javax.swing.JSeparator();
        direccion_txt = new javax.swing.JLabel();
        direccion_input = new javax.swing.JTextField();
        jSeparator_direccion2 = new javax.swing.JSeparator();
        jPanel_registrar2 = new javax.swing.JPanel();
        jLabel_registrar2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        ingresarUsuario = new javax.swing.JPanel();
        telefono_txt = new javax.swing.JLabel();
        telefono_input = new javax.swing.JTextField();
        jSeparator_telefono = new javax.swing.JSeparator();
        fechaNacimiento_txt = new javax.swing.JLabel();
        fechaNacimiento_input = new javax.swing.JTextField();
        jSeparator_fNac = new javax.swing.JSeparator();
        jPanel_registrar = new javax.swing.JPanel();
        jLabel_registrar = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        ingresarVendedor = new javax.swing.JPanel();
        jLabel_telefono1 = new javax.swing.JLabel();
        jTextField_telefono1 = new javax.swing.JTextField();
        jSeparator_telefono1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(660, 460));
        setMinimumSize(new java.awt.Dimension(660, 460));

        ingresarPersona.setBackground(new java.awt.Color(51, 51, 51));
        ingresarPersona.setMaximumSize(new java.awt.Dimension(660, 460));
        ingresarPersona.setMinimumSize(new java.awt.Dimension(660, 460));
        ingresarPersona.setPreferredSize(new java.awt.Dimension(660, 460));
        ingresarPersona.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo_txt.setBackground(new java.awt.Color(255, 255, 255));
        titulo_txt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        titulo_txt.setForeground(new java.awt.Color(255, 255, 255));
        titulo_txt.setText("Ingresar ");
        ingresarPersona.add(titulo_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, -1, -1));

        rut_txt.setBackground(new java.awt.Color(255, 255, 255));
        rut_txt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rut_txt.setForeground(new java.awt.Color(255, 255, 255));
        rut_txt.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        rut_txt.setText("Rut:");
        ingresarPersona.add(rut_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 130, -1));

        rut_input.setBackground(new java.awt.Color(51, 51, 51));
        rut_input.setForeground(new java.awt.Color(102, 102, 102));
        rut_input.setText("00.000.000-K");
        rut_input.setBorder(null);
        ingresarPersona.add(rut_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 270, -1));
        ingresarPersona.add(jSeparator_rut2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 270, 10));

        nombre_txt.setBackground(new java.awt.Color(255, 255, 255));
        nombre_txt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        nombre_txt.setForeground(new java.awt.Color(255, 255, 255));
        nombre_txt.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        nombre_txt.setText("Nombre:");
        ingresarPersona.add(nombre_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 130, -1));

        nombre_input.setBackground(new java.awt.Color(51, 51, 51));
        nombre_input.setForeground(new java.awt.Color(102, 102, 102));
        nombre_input.setText("Juan Navarro");
        nombre_input.setBorder(null);
        ingresarPersona.add(nombre_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 270, -1));
        ingresarPersona.add(jSeparator_nombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 270, 10));

        correo_txt.setBackground(new java.awt.Color(255, 255, 255));
        correo_txt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        correo_txt.setForeground(new java.awt.Color(255, 255, 255));
        correo_txt.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        correo_txt.setText("Correo:");
        ingresarPersona.add(correo_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 130, -1));

        correo_input.setBackground(new java.awt.Color(51, 51, 51));
        correo_input.setForeground(new java.awt.Color(102, 102, 102));
        correo_input.setText("correoFalso@dominioFalso.cl");
        correo_input.setBorder(null);
        ingresarPersona.add(correo_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 270, -1));
        ingresarPersona.add(jSeparator_correo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, 270, 10));

        comuna_txt.setBackground(new java.awt.Color(255, 255, 255));
        comuna_txt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        comuna_txt.setForeground(new java.awt.Color(255, 255, 255));
        comuna_txt.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        comuna_txt.setText("Comuna:");
        ingresarPersona.add(comuna_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 130, -1));

        comuna_input.setBackground(new java.awt.Color(51, 51, 51));
        comuna_input.setForeground(new java.awt.Color(102, 102, 102));
        comuna_input.setText("San Joaquin");
        comuna_input.setBorder(null);
        ingresarPersona.add(comuna_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 270, -1));
        ingresarPersona.add(jSeparator_comuna1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, 270, 10));

        direccion_txt.setBackground(new java.awt.Color(255, 255, 255));
        direccion_txt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        direccion_txt.setForeground(new java.awt.Color(255, 255, 255));
        direccion_txt.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        direccion_txt.setText("Direccion:");
        ingresarPersona.add(direccion_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 130, -1));

        direccion_input.setBackground(new java.awt.Color(51, 51, 51));
        direccion_input.setForeground(new java.awt.Color(102, 102, 102));
        direccion_input.setText("Industrias 111");
        direccion_input.setBorder(null);
        ingresarPersona.add(direccion_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, 270, -1));
        ingresarPersona.add(jSeparator_direccion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, 270, 10));

        jPanel_registrar2.setBackground(new java.awt.Color(0, 153, 153));

        jLabel_registrar2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel_registrar2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_registrar2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_registrar2.setText("Registrar");
        jLabel_registrar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_registrar2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel_registrar2Layout = new javax.swing.GroupLayout(jPanel_registrar2);
        jPanel_registrar2.setLayout(jPanel_registrar2Layout);
        jPanel_registrar2Layout.setHorizontalGroup(
            jPanel_registrar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(jPanel_registrar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel_registrar2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel_registrar2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel_registrar2Layout.setVerticalGroup(
            jPanel_registrar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
            .addGroup(jPanel_registrar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel_registrar2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel_registrar2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        ingresarPersona.add(jPanel_registrar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 330, -1, -1));

        jButton2.setText("Volver");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        ingresarPersona.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 380, -1, -1));

        ingresarUsuario.setBackground(new java.awt.Color(51, 51, 51));
        ingresarUsuario.setMaximumSize(new java.awt.Dimension(660, 460));
        ingresarUsuario.setMinimumSize(new java.awt.Dimension(660, 460));
        ingresarUsuario.setPreferredSize(new java.awt.Dimension(660, 460));
        ingresarUsuario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        telefono_txt.setBackground(new java.awt.Color(255, 255, 255));
        telefono_txt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        telefono_txt.setForeground(new java.awt.Color(255, 255, 255));
        telefono_txt.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        telefono_txt.setText("Telefono:");
        ingresarUsuario.add(telefono_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 130, -1));

        telefono_input.setBackground(new java.awt.Color(51, 51, 51));
        telefono_input.setForeground(new java.awt.Color(102, 102, 102));
        telefono_input.setText("+56 9 0000 0000");
        telefono_input.setBorder(null);
        ingresarUsuario.add(telefono_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, 270, -1));
        ingresarUsuario.add(jSeparator_telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, 270, 10));

        fechaNacimiento_txt.setBackground(new java.awt.Color(255, 255, 255));
        fechaNacimiento_txt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        fechaNacimiento_txt.setForeground(new java.awt.Color(255, 255, 255));
        fechaNacimiento_txt.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        fechaNacimiento_txt.setText("Fecha nacimiento:");
        ingresarUsuario.add(fechaNacimiento_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 130, -1));

        fechaNacimiento_input.setBackground(new java.awt.Color(51, 51, 51));
        fechaNacimiento_input.setForeground(new java.awt.Color(102, 102, 102));
        fechaNacimiento_input.setText("dd-MM-yy");
        fechaNacimiento_input.setBorder(null);
        ingresarUsuario.add(fechaNacimiento_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, 270, -1));
        ingresarUsuario.add(jSeparator_fNac, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, 270, 10));

        jPanel_registrar.setBackground(new java.awt.Color(0, 153, 153));

        jLabel_registrar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel_registrar.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_registrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_registrar.setText("Registrar");
        jLabel_registrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_registrarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel_registrarLayout = new javax.swing.GroupLayout(jPanel_registrar);
        jPanel_registrar.setLayout(jPanel_registrarLayout);
        jPanel_registrarLayout.setHorizontalGroup(
            jPanel_registrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(jPanel_registrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel_registrarLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel_registrar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel_registrarLayout.setVerticalGroup(
            jPanel_registrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
            .addGroup(jPanel_registrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel_registrarLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel_registrar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        ingresarUsuario.add(jPanel_registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 330, -1, -1));

        jButton1.setText("Volver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        ingresarUsuario.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 380, -1, -1));

        ingresarPersona.add(ingresarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 460));

        ingresarVendedor.setBackground(new java.awt.Color(51, 51, 51));
        ingresarVendedor.setMaximumSize(new java.awt.Dimension(660, 460));
        ingresarVendedor.setMinimumSize(new java.awt.Dimension(660, 460));
        ingresarVendedor.setPreferredSize(new java.awt.Dimension(660, 460));
        ingresarVendedor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_telefono1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_telefono1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_telefono1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_telefono1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel_telefono1.setText("Fono:");
        ingresarVendedor.add(jLabel_telefono1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 247, 130, -1));

        jTextField_telefono1.setBackground(new java.awt.Color(51, 51, 51));
        jTextField_telefono1.setForeground(new java.awt.Color(102, 102, 102));
        jTextField_telefono1.setText("+56 9 0000 0000");
        jTextField_telefono1.setBorder(null);
        ingresarVendedor.add(jTextField_telefono1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, 270, -1));
        ingresarVendedor.add(jSeparator_telefono1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, 270, 10));

        ingresarPersona.add(ingresarVendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 460));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(ingresarPersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(ingresarPersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_registrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_registrarMouseClicked
        /*
        String nombre = jTextField_nombre.getText();
        verificarCamposEnBlanco(nombre, "nombre");

        String fecha = fechaNacimiento_input.getText();
        verificarCamposEnBlanco(fecha, "fecha");

        String direccion = jTextField_direccion.getText();
        verificarCamposEnBlanco(direccion, "direccion");

        String comuna = jTextField_comuna.getText();
        verificarCamposEnBlanco(comuna, "comuna");

        String telefono = telefono_input.getText();
        verificarCamposEnBlanco(telefono, "telefono");

        String rut = jTextField_rut.getText();
        verificarCamposEnBlanco(rut, "rut");

        String correo = jTextField_correo.getText();
        verificarCamposEnBlanco(correo, "correo");
        */
        /*
        try{
            Visualizador.sistema.ingresarUsuario(fecha, comuna, telefono, rut, nombre, direccion, correo);
            JOptionPane.showMessageDialog(null,"Usuario ingresado.");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e.getMessage());
        }*/
    }//GEN-LAST:event_jLabel_registrarMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel_registrar2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_registrar2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_registrar2MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField comuna_input;
    private javax.swing.JLabel comuna_txt;
    private javax.swing.JTextField correo_input;
    private javax.swing.JLabel correo_txt;
    private javax.swing.JTextField direccion_input;
    private javax.swing.JLabel direccion_txt;
    private javax.swing.JTextField fechaNacimiento_input;
    private javax.swing.JLabel fechaNacimiento_txt;
    private javax.swing.JPanel ingresarPersona;
    private javax.swing.JPanel ingresarUsuario;
    private javax.swing.JPanel ingresarVendedor;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel_registrar;
    private javax.swing.JLabel jLabel_registrar2;
    private javax.swing.JLabel jLabel_telefono1;
    private javax.swing.JPanel jPanel_registrar;
    private javax.swing.JPanel jPanel_registrar2;
    private javax.swing.JSeparator jSeparator_comuna1;
    private javax.swing.JSeparator jSeparator_correo2;
    private javax.swing.JSeparator jSeparator_direccion2;
    private javax.swing.JSeparator jSeparator_fNac;
    private javax.swing.JSeparator jSeparator_nombre2;
    private javax.swing.JSeparator jSeparator_rut2;
    private javax.swing.JSeparator jSeparator_telefono;
    private javax.swing.JSeparator jSeparator_telefono1;
    private javax.swing.JTextField jTextField_telefono1;
    private javax.swing.JTextField nombre_input;
    private javax.swing.JLabel nombre_txt;
    private javax.swing.JTextField rut_input;
    private javax.swing.JLabel rut_txt;
    private javax.swing.JTextField telefono_input;
    private javax.swing.JLabel telefono_txt;
    private javax.swing.JLabel titulo_txt;
    // End of variables declaration//GEN-END:variables
}
