/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import javax.swing.JOptionPane;

/**
 *
 * @author thoma
 */
public class IngresarObj extends javax.swing.JPanel {

    /**
     * Creates new form IngresarUsuario
     */
    public IngresarObj() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ingresarUsuario = new javax.swing.JPanel();
        jLabel_Titulo = new javax.swing.JLabel();
        jLabel_rut = new javax.swing.JLabel();
        jTextField_rut = new javax.swing.JTextField();
        jSeparator_rut = new javax.swing.JSeparator();
        jLabel_nombre = new javax.swing.JLabel();
        jTextField_nombre = new javax.swing.JTextField();
        jSeparator_nombre = new javax.swing.JSeparator();
        jLabel_correo = new javax.swing.JLabel();
        jTextField_correo = new javax.swing.JTextField();
        jSeparator_correo = new javax.swing.JSeparator();
        jLabel_comuna = new javax.swing.JLabel();
        jTextField_comuna = new javax.swing.JTextField();
        jSeparator_comuna = new javax.swing.JSeparator();
        jLabel_direccion = new javax.swing.JLabel();
        jTextField_direccion = new javax.swing.JTextField();
        jSeparator_direccion = new javax.swing.JSeparator();
        jLabel_telefono = new javax.swing.JLabel();
        jTextField_telefono = new javax.swing.JTextField();
        jSeparator_telefono = new javax.swing.JSeparator();
        jLabel_fNac = new javax.swing.JLabel();
        jTextField_fNac = new javax.swing.JTextField();
        jSeparator_fNac = new javax.swing.JSeparator();
        jPanel_menu = new javax.swing.JPanel();
        jLabel_menu = new javax.swing.JLabel();
        jPanel_registrar = new javax.swing.JPanel();
        jLabel_registrar = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(138, 25));
        setMinimumSize(new java.awt.Dimension(138, 25));
        setPreferredSize(new java.awt.Dimension(610, 460));

        ingresarUsuario.setBackground(new java.awt.Color(51, 51, 51));
        ingresarUsuario.setMinimumSize(new java.awt.Dimension(0, 0));
        ingresarUsuario.setPreferredSize(new java.awt.Dimension(610, 460));
        ingresarUsuario.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                ingresarUsuarioMouseDragged(evt);
            }
        });
        ingresarUsuario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_Titulo.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_Titulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel_Titulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Titulo.setText("Ingresar Usuario");
        ingresarUsuario.add(jLabel_Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, -1, -1));

        jLabel_rut.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_rut.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_rut.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_rut.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel_rut.setText("Rut:");
        ingresarUsuario.add(jLabel_rut, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 130, -1));

        jTextField_rut.setBackground(new java.awt.Color(51, 51, 51));
        jTextField_rut.setForeground(new java.awt.Color(102, 102, 102));
        jTextField_rut.setText("00.000.000-K");
        jTextField_rut.setBorder(null);
        ingresarUsuario.add(jTextField_rut, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 270, -1));
        ingresarUsuario.add(jSeparator_rut, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 270, 10));

        jLabel_nombre.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_nombre.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_nombre.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_nombre.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel_nombre.setText("Nombre:");
        ingresarUsuario.add(jLabel_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 130, -1));

        jTextField_nombre.setBackground(new java.awt.Color(51, 51, 51));
        jTextField_nombre.setForeground(new java.awt.Color(102, 102, 102));
        jTextField_nombre.setText("Juan Navarro");
        jTextField_nombre.setBorder(null);
        ingresarUsuario.add(jTextField_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 270, -1));
        ingresarUsuario.add(jSeparator_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 270, 10));

        jLabel_correo.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_correo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_correo.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_correo.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel_correo.setText("Correo:");
        ingresarUsuario.add(jLabel_correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 130, -1));

        jTextField_correo.setBackground(new java.awt.Color(51, 51, 51));
        jTextField_correo.setForeground(new java.awt.Color(102, 102, 102));
        jTextField_correo.setText("correoFalso@dominioFalso.cl");
        jTextField_correo.setBorder(null);
        ingresarUsuario.add(jTextField_correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 270, -1));
        ingresarUsuario.add(jSeparator_correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, 270, 10));

        jLabel_comuna.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_comuna.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_comuna.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_comuna.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel_comuna.setText("Comuna:");
        ingresarUsuario.add(jLabel_comuna, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 130, -1));

        jTextField_comuna.setBackground(new java.awt.Color(51, 51, 51));
        jTextField_comuna.setForeground(new java.awt.Color(102, 102, 102));
        jTextField_comuna.setText("San Joaquin");
        jTextField_comuna.setBorder(null);
        ingresarUsuario.add(jTextField_comuna, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 270, -1));
        ingresarUsuario.add(jSeparator_comuna, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, 270, 10));

        jLabel_direccion.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_direccion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_direccion.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_direccion.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel_direccion.setText("Direccion:");
        ingresarUsuario.add(jLabel_direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 130, -1));

        jTextField_direccion.setBackground(new java.awt.Color(51, 51, 51));
        jTextField_direccion.setForeground(new java.awt.Color(102, 102, 102));
        jTextField_direccion.setText("Industrias 111");
        jTextField_direccion.setBorder(null);
        ingresarUsuario.add(jTextField_direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, 270, -1));
        ingresarUsuario.add(jSeparator_direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, 270, 10));

        jLabel_telefono.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_telefono.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_telefono.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_telefono.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel_telefono.setText("Telefono:");
        ingresarUsuario.add(jLabel_telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 130, -1));

        jTextField_telefono.setBackground(new java.awt.Color(51, 51, 51));
        jTextField_telefono.setForeground(new java.awt.Color(102, 102, 102));
        jTextField_telefono.setText("+56 9 0000 0000");
        jTextField_telefono.setBorder(null);
        ingresarUsuario.add(jTextField_telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, 270, -1));
        ingresarUsuario.add(jSeparator_telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, 270, 10));

        jLabel_fNac.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_fNac.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_fNac.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_fNac.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel_fNac.setText("Fecha nacimiento:");
        ingresarUsuario.add(jLabel_fNac, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 130, -1));

        jTextField_fNac.setBackground(new java.awt.Color(51, 51, 51));
        jTextField_fNac.setForeground(new java.awt.Color(102, 102, 102));
        jTextField_fNac.setText("dd-MM-yy");
        jTextField_fNac.setBorder(null);
        ingresarUsuario.add(jTextField_fNac, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, 270, -1));
        ingresarUsuario.add(jSeparator_fNac, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, 270, 10));

        jPanel_menu.setBackground(new java.awt.Color(0, 153, 153));

        jLabel_menu.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel_menu.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_menu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_menu.setText("ATRAS");
        jLabel_menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_menuMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel_menuLayout = new javax.swing.GroupLayout(jPanel_menu);
        jPanel_menu.setLayout(jPanel_menuLayout);
        jPanel_menuLayout.setHorizontalGroup(
            jPanel_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(jPanel_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel_menuLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel_menuLayout.setVerticalGroup(
            jPanel_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
            .addGroup(jPanel_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel_menuLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        ingresarUsuario.add(jPanel_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, -1, -1));

        jPanel_registrar.setBackground(new java.awt.Color(0, 153, 153));

        jLabel_registrar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel_registrar.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_registrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_registrar.setText("Registrar");
        jLabel_registrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_registrarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel_registrarLayout = new javax.swing.GroupLayout(jPanel_registrar);
        jPanel_registrar.setLayout(jPanel_registrarLayout);
        jPanel_registrarLayout.setHorizontalGroup(
            jPanel_registrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(jPanel_registrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel_registrarLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel_registrar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel_registrarLayout.setVerticalGroup(
            jPanel_registrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
            .addGroup(jPanel_registrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel_registrarLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel_registrar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        ingresarUsuario.add(jPanel_registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 330, -1, -1));

        jButton1.setText("Volver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        ingresarUsuario.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 380, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(ingresarUsuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(ingresarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_menuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_menuMouseClicked

    }//GEN-LAST:event_jLabel_menuMouseClicked
    /**
     * Este boton hace el control de error para los diferentes inputs del usuario llamando a la funcion de abajo.
     * @param evt 
     */
    private void jLabel_registrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_registrarMouseClicked

        String nombre = jTextField_nombre.getText();
        verificarCamposEnBlanco(nombre, "nombre");

        String fecha = jTextField_fNac.getText();
        verificarCamposEnBlanco(fecha, "fecha");

        String direccion = jTextField_direccion.getText();
        verificarCamposEnBlanco(direccion, "direccion");
 
        String comuna = jTextField_comuna.getText();
        verificarCamposEnBlanco(comuna, "comuna");

        String telefono = jTextField_telefono.getText();
        verificarCamposEnBlanco(telefono, "telefono");

        String rut = jTextField_rut.getText();
        verificarCamposEnBlanco(rut, "rut");

        String correo = jTextField_correo.getText();
        verificarCamposEnBlanco(correo, "correo");
        /*
        try{
            Visualizador.sistema.ingresarUsuario(fecha, comuna, telefono, rut, nombre, direccion, correo);
            JOptionPane.showMessageDialog(null,"Usuario ingresado.");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e.getMessage());   
        }*/
    }//GEN-LAST:event_jLabel_registrarMouseClicked
    public void verificarCamposEnBlanco(String campo,String nombre){
        if(campo.equals("")){
            JOptionPane.showMessageDialog(null,"El/La "+nombre+" no puede estar en blanco.");
        }
    }
    private void ingresarUsuarioMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingresarUsuarioMouseDragged
        //BORRAR
    }//GEN-LAST:event_ingresarUsuarioMouseDragged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Menu_admin menu_admin = new Menu_admin();
        menu_admin.setSize(660, 460);
        menu_admin.setLocation(0,0);

        ingresarUsuario.removeAll();
        ingresarUsuario.add(menu_admin,new org.netbeans.lib.awtextra.AbsoluteConstraints(0,0,-1,-1));
        ingresarUsuario.revalidate();
        ingresarUsuario.repaint();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ingresarUsuario;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel_Titulo;
    private javax.swing.JLabel jLabel_comuna;
    private javax.swing.JLabel jLabel_correo;
    private javax.swing.JLabel jLabel_direccion;
    private javax.swing.JLabel jLabel_fNac;
    private javax.swing.JLabel jLabel_menu;
    private javax.swing.JLabel jLabel_nombre;
    private javax.swing.JLabel jLabel_registrar;
    private javax.swing.JLabel jLabel_rut;
    private javax.swing.JLabel jLabel_telefono;
    private javax.swing.JPanel jPanel_menu;
    private javax.swing.JPanel jPanel_registrar;
    private javax.swing.JSeparator jSeparator_comuna;
    private javax.swing.JSeparator jSeparator_correo;
    private javax.swing.JSeparator jSeparator_direccion;
    private javax.swing.JSeparator jSeparator_fNac;
    private javax.swing.JSeparator jSeparator_nombre;
    private javax.swing.JSeparator jSeparator_rut;
    private javax.swing.JSeparator jSeparator_telefono;
    private javax.swing.JTextField jTextField_comuna;
    private javax.swing.JTextField jTextField_correo;
    private javax.swing.JTextField jTextField_direccion;
    private javax.swing.JTextField jTextField_fNac;
    private javax.swing.JTextField jTextField_nombre;
    private javax.swing.JTextField jTextField_rut;
    private javax.swing.JTextField jTextField_telefono;
    // End of variables declaration//GEN-END:variables
}
