/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import javax.swing.JOptionPane;

/**
 *
 * @author thoma
 */
public class IngresarRegistros extends javax.swing.JFrame {

    private String tipo_registro;
    public IngresarRegistros(String nombre_registro) {
        initComponents();
        ocultarPaneles();
        
        tipo_registro = nombre_registro;
        if(nombre_registro.equals("Usuario")){
            tipo_registro = "persona";
            titulo_txt.setText("Ingresar Usuario");
            ingresarPersona.setVisible(true);
            ingresarUsuario.setVisible(true);
        }else if(nombre_registro.equals("Vendedor") || nombre_registro.equals("Desarrollador")){
            tipo_registro = "persona";
            titulo_txt.setText(titulo_txt.getText()+nombre_registro);
            ingresarPersona.setVisible(true);
            ingresarVend_Desarr.setVisible(true);
        
        }else if(nombre_registro.equalsIgnoreCase("videojuego")){

        }else{
                
        }
    }
    private void ocultarPaneles(){
        ingresarPersona.setVisible(false);
        ingresarUsuario.setVisible(false);
        ingresarVend_Desarr.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ingresarPersona = new javax.swing.JPanel();
        titulo_txt = new javax.swing.JLabel();
        rut_txt = new javax.swing.JLabel();
        rut_input = new javax.swing.JTextField();
        jSeparator_rut2 = new javax.swing.JSeparator();
        nombre_txt = new javax.swing.JLabel();
        nombre_input = new javax.swing.JTextField();
        jSeparator_nombre2 = new javax.swing.JSeparator();
        correo_txt = new javax.swing.JLabel();
        correo_input = new javax.swing.JTextField();
        jSeparator_correo2 = new javax.swing.JSeparator();
        comuna_txt = new javax.swing.JLabel();
        comuna_input = new javax.swing.JTextField();
        jSeparator_comuna1 = new javax.swing.JSeparator();
        direccion_txt = new javax.swing.JLabel();
        direccion_input = new javax.swing.JTextField();
        jSeparator_direccion2 = new javax.swing.JSeparator();
        ingresar_button = new javax.swing.JButton();
        registrar_button = new javax.swing.JButton();
        ingresarUsuario = new javax.swing.JPanel();
        telefono_txt = new javax.swing.JLabel();
        telefono_input = new javax.swing.JTextField();
        jSeparator_telefono = new javax.swing.JSeparator();
        fechaNacimiento_txt = new javax.swing.JLabel();
        fechaNacimiento_input = new javax.swing.JTextField();
        jSeparator_fNac = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        ingresarVend_Desarr = new javax.swing.JPanel();
        fono_txt = new javax.swing.JLabel();
        fono_input = new javax.swing.JTextField();
        fono_separator = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(660, 460));
        setMinimumSize(new java.awt.Dimension(660, 460));

        ingresarPersona.setBackground(new java.awt.Color(51, 51, 51));
        ingresarPersona.setMaximumSize(new java.awt.Dimension(660, 460));
        ingresarPersona.setMinimumSize(new java.awt.Dimension(660, 460));
        ingresarPersona.setPreferredSize(new java.awt.Dimension(660, 460));
        ingresarPersona.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo_txt.setBackground(new java.awt.Color(255, 255, 255));
        titulo_txt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        titulo_txt.setForeground(new java.awt.Color(255, 255, 255));
        titulo_txt.setText("Ingresar ");
        ingresarPersona.add(titulo_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, -1, -1));

        rut_txt.setBackground(new java.awt.Color(255, 255, 255));
        rut_txt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rut_txt.setForeground(new java.awt.Color(255, 255, 255));
        rut_txt.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        rut_txt.setText("Rut:");
        ingresarPersona.add(rut_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 130, -1));

        rut_input.setBackground(new java.awt.Color(51, 51, 51));
        rut_input.setForeground(new java.awt.Color(102, 102, 102));
        rut_input.setText("00.000.000-K");
        rut_input.setBorder(null);
        ingresarPersona.add(rut_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 270, -1));
        ingresarPersona.add(jSeparator_rut2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 270, 10));

        nombre_txt.setBackground(new java.awt.Color(255, 255, 255));
        nombre_txt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        nombre_txt.setForeground(new java.awt.Color(255, 255, 255));
        nombre_txt.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        nombre_txt.setText("Nombre:");
        ingresarPersona.add(nombre_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 130, -1));

        nombre_input.setBackground(new java.awt.Color(51, 51, 51));
        nombre_input.setForeground(new java.awt.Color(102, 102, 102));
        nombre_input.setText("Juan Navarro");
        nombre_input.setBorder(null);
        ingresarPersona.add(nombre_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 270, -1));
        ingresarPersona.add(jSeparator_nombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 270, 10));

        correo_txt.setBackground(new java.awt.Color(255, 255, 255));
        correo_txt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        correo_txt.setForeground(new java.awt.Color(255, 255, 255));
        correo_txt.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        correo_txt.setText("Correo:");
        ingresarPersona.add(correo_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 130, -1));

        correo_input.setBackground(new java.awt.Color(51, 51, 51));
        correo_input.setForeground(new java.awt.Color(102, 102, 102));
        correo_input.setText("correoFalso@dominioFalso.cl");
        correo_input.setBorder(null);
        ingresarPersona.add(correo_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 270, -1));
        ingresarPersona.add(jSeparator_correo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, 270, 10));

        comuna_txt.setBackground(new java.awt.Color(255, 255, 255));
        comuna_txt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        comuna_txt.setForeground(new java.awt.Color(255, 255, 255));
        comuna_txt.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        comuna_txt.setText("Comuna:");
        ingresarPersona.add(comuna_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 130, -1));

        comuna_input.setBackground(new java.awt.Color(51, 51, 51));
        comuna_input.setForeground(new java.awt.Color(102, 102, 102));
        comuna_input.setText("San Joaquin");
        comuna_input.setBorder(null);
        ingresarPersona.add(comuna_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 270, -1));
        ingresarPersona.add(jSeparator_comuna1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, 270, 10));

        direccion_txt.setBackground(new java.awt.Color(255, 255, 255));
        direccion_txt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        direccion_txt.setForeground(new java.awt.Color(255, 255, 255));
        direccion_txt.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        direccion_txt.setText("Direccion:");
        ingresarPersona.add(direccion_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 130, -1));

        direccion_input.setBackground(new java.awt.Color(51, 51, 51));
        direccion_input.setForeground(new java.awt.Color(102, 102, 102));
        direccion_input.setText("Industrias 111");
        direccion_input.setBorder(null);
        ingresarPersona.add(direccion_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, 270, -1));
        ingresarPersona.add(jSeparator_direccion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, 270, 10));

        ingresar_button.setText("Volver");
        ingresar_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresar_buttonActionPerformed(evt);
            }
        });
        ingresarPersona.add(ingresar_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 380, -1, -1));

        registrar_button.setText("Registrar");
        registrar_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrar_buttonActionPerformed(evt);
            }
        });
        ingresarPersona.add(registrar_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 380, -1, -1));

        ingresarUsuario.setBackground(new java.awt.Color(51, 51, 51));
        ingresarUsuario.setMaximumSize(new java.awt.Dimension(660, 460));
        ingresarUsuario.setMinimumSize(new java.awt.Dimension(660, 460));
        ingresarUsuario.setPreferredSize(new java.awt.Dimension(660, 460));
        ingresarUsuario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        telefono_txt.setBackground(new java.awt.Color(255, 255, 255));
        telefono_txt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        telefono_txt.setForeground(new java.awt.Color(255, 255, 255));
        telefono_txt.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        telefono_txt.setText("Telefono:");
        ingresarUsuario.add(telefono_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 130, -1));

        telefono_input.setBackground(new java.awt.Color(51, 51, 51));
        telefono_input.setForeground(new java.awt.Color(102, 102, 102));
        telefono_input.setText("+56 9 0000 0000");
        telefono_input.setBorder(null);
        ingresarUsuario.add(telefono_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, 270, -1));
        ingresarUsuario.add(jSeparator_telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, 270, 10));

        fechaNacimiento_txt.setBackground(new java.awt.Color(255, 255, 255));
        fechaNacimiento_txt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        fechaNacimiento_txt.setForeground(new java.awt.Color(255, 255, 255));
        fechaNacimiento_txt.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        fechaNacimiento_txt.setText("Fecha nacimiento:");
        ingresarUsuario.add(fechaNacimiento_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 130, -1));

        fechaNacimiento_input.setBackground(new java.awt.Color(51, 51, 51));
        fechaNacimiento_input.setForeground(new java.awt.Color(102, 102, 102));
        fechaNacimiento_input.setText("dd-MM-yy");
        fechaNacimiento_input.setBorder(null);
        ingresarUsuario.add(fechaNacimiento_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, 270, -1));
        ingresarUsuario.add(jSeparator_fNac, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, 270, 10));

        jButton1.setText("Volver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        ingresarUsuario.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 380, -1, -1));

        ingresarPersona.add(ingresarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 460));

        ingresarVend_Desarr.setBackground(new java.awt.Color(51, 51, 51));
        ingresarVend_Desarr.setMaximumSize(new java.awt.Dimension(660, 460));
        ingresarVend_Desarr.setMinimumSize(new java.awt.Dimension(660, 460));
        ingresarVend_Desarr.setPreferredSize(new java.awt.Dimension(660, 460));
        ingresarVend_Desarr.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fono_txt.setBackground(new java.awt.Color(255, 255, 255));
        fono_txt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        fono_txt.setForeground(new java.awt.Color(255, 255, 255));
        fono_txt.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        fono_txt.setText("Fono:");
        ingresarVend_Desarr.add(fono_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 247, 130, -1));

        fono_input.setBackground(new java.awt.Color(51, 51, 51));
        fono_input.setForeground(new java.awt.Color(102, 102, 102));
        fono_input.setText("+56 9 0000 0000");
        fono_input.setBorder(null);
        ingresarVend_Desarr.add(fono_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, 270, -1));
        ingresarVend_Desarr.add(fono_separator, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, 270, 10));

        ingresarPersona.add(ingresarVend_Desarr, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 460));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(ingresarPersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 472, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(ingresarPersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

    }//GEN-LAST:event_jButton1ActionPerformed

    private void ingresar_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresar_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ingresar_buttonActionPerformed

    private void registrar_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrar_buttonActionPerformed
        System.out.println(tipo_registro);
        if(tipo_registro.equalsIgnoreCase("persona")){
            String rut = rut_input.getText();
            String nombre = nombre_input.getText();
            String correo = correo_input.getText();
            String direccion= direccion_input.getText();
            String tipo_persona = titulo_txt.getText().replace("Ingresar ", "");
            System.out.println(tipo_persona);
            if(tipo_persona.equals("Usuario")){
                String comuna = comuna_input.getText();
                String telefono = telefono_input.getText();
                String fecha_de_nacimiento = fechaNacimiento_input.getText();
                try{
                    Visualizador.sistema.ingresarUsuario(rut, nombre, direccion, correo, fecha_de_nacimiento, comuna, telefono);
                    JOptionPane.showMessageDialog(null, tipo_persona+" ingresado", "Validación", 1);
                }catch(Exception e){
                    JOptionPane.showMessageDialog(null, e.getMessage(), "Validación", 1);
                }
                
            }else{
                String fono = fono_input.getText();
                String titulo = titulo_txt.getText().replaceAll("Menu ", "");
                try{
                    if(tipo_persona.equals("Vendedor")){
                        Visualizador.sistema.ingresarVendedor(rut, nombre, direccion, correo, fono);
                    }else{
                        Visualizador.sistema.ingresarDesarrollador(rut, nombre, direccion, correo, fono);
                    }
                    JOptionPane.showMessageDialog(null, tipo_persona+" ingresado", "Validación", 1);
                }catch(Exception e){
                    JOptionPane.showMessageDialog(null, e.getMessage(), "Validación", 1);
                }
            }
        }else if(tipo_registro.equals("Videojuego")){

        }else{
                
        }
    }//GEN-LAST:event_registrar_buttonActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField comuna_input;
    private javax.swing.JLabel comuna_txt;
    private javax.swing.JTextField correo_input;
    private javax.swing.JLabel correo_txt;
    private javax.swing.JTextField direccion_input;
    private javax.swing.JLabel direccion_txt;
    private javax.swing.JTextField fechaNacimiento_input;
    private javax.swing.JLabel fechaNacimiento_txt;
    private javax.swing.JTextField fono_input;
    private javax.swing.JSeparator fono_separator;
    private javax.swing.JLabel fono_txt;
    private javax.swing.JPanel ingresarPersona;
    private javax.swing.JPanel ingresarUsuario;
    private javax.swing.JPanel ingresarVend_Desarr;
    private javax.swing.JButton ingresar_button;
    private javax.swing.JButton jButton1;
    private javax.swing.JSeparator jSeparator_comuna1;
    private javax.swing.JSeparator jSeparator_correo2;
    private javax.swing.JSeparator jSeparator_direccion2;
    private javax.swing.JSeparator jSeparator_fNac;
    private javax.swing.JSeparator jSeparator_nombre2;
    private javax.swing.JSeparator jSeparator_rut2;
    private javax.swing.JSeparator jSeparator_telefono;
    private javax.swing.JTextField nombre_input;
    private javax.swing.JLabel nombre_txt;
    private javax.swing.JButton registrar_button;
    private javax.swing.JTextField rut_input;
    private javax.swing.JLabel rut_txt;
    private javax.swing.JTextField telefono_input;
    private javax.swing.JLabel telefono_txt;
    private javax.swing.JLabel titulo_txt;
    // End of variables declaration//GEN-END:variables
}
